- name: Load govc Vars
  include_vars: "{{ role_path }}/vars/govc_vars.yml"

- name: Remove "{{ hostname }}"
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    cluster: "{{ vcenter_cluster }}"
    name: "{{ hostname }}"
    state: absent
  delegate_to: localhost
  register: facts
