---
- name: Set the state of a virtual machine to poweroff
  vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    folder: "{{ vcenter_folder_full }}"
    name: "{{ hostname }}"
    state: powered-off
  delegate_to: localhost
  register: new_vm
  with_items:
    "{{ groups['dhcpclients'] | sort }}"

