- name: Install Docker Registry | install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-distribution

- name: Install Docker Registry | enable docker registry
  service:
    name: docker-distribution
    state: started
    enabled: yes
