- name: install subscription-manager
  package:
    name: subscription-manager
    state: present

#- include_vars: rhelpass.yml
#- name: Put the rhelpass text in the tmp directory on the remote server.
#  copy:
#    content="{{rhelpass}}"
#    dest=/tmp/rhelpass.txt

- name: Register and attach to pool
  redhat_subscription:
    state: present
    username: "{{rheluser}}"
    password: "{{rhelpass}}"
    pool_ids: "{{rhelpool}}"
  register: loginrhel

- name: Detach existing subscriptions
  shell: "subscription-manager repos --disable=*"
  when: "loginrhel.changed == true"

- name: Attach to needed subscriptions
  shell: 'subscription-manager repos --enable="rhel-7-server-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-server-rhscl-7-rpms" --enable="rhel-7-server-optional-rpms" --enable="rhel-ha-for-rhel-7-server-rpms"'
  when: "loginrhel.changed == true"

#- name: Log into rhel io registry 
#  docker_login:
#    registry: registry.redhat.io
#    username: "{{rheluser}}"
#    password: "{{rhelpass}}"
#  when: "inventory_hostname not in groups['lb']"
