[rhel-7-server-rpms]
name=rhel-7-server-rpms
baseurl=http://{{ yumrepo_url}}/rhel-7-server-rpms
enabled=1
gpgcheck=0

[rhel-7-server-extras-rpms]
name=rhel-7-server-extras-rpms
baseurl=http://{{ yumrepo_url}}/rhel-7-server-extras-rpms
enabled=1
gpgcheck=0

[rhel-server-rhscl-7-rpms]
name=rhel-server-rhscl-7-rpms
baseurl=http://{{ yumrepo_url}}/rhel-server-rhscl-7-rpms
enabled=1
gpgcheck=0

[rhel-7-server-optional-rpms]
name=rhel-7-server-optional-rpms
baseurl=http://{{ yumrepo_url}}/rhel-7-server-optional-rpms
enabled=1
gpgcheck=0

[rhel-ha-for-rhel-7-server-rpms]
name=rhel-ha-for-rhel-7-server-rpms
baseurl=http://{{ yumrepo_url}}/rhel-ha-for-rhel-7-server-rpms
enabled=1
gpgcheck=0
